### ISSUE TITLE
can't add certificate for https here

### ISSUE THREAD

**Issue by yosefy** [terraform-aws-modules/terraform-aws-elb#1]
it fails if i add listener like that:

```hcl
  listener = [
    {
      instance_port     = "8020"
      instance_protocol = "HTTP"
      lb_port           = "443"
      lb_protocol       = "SSL"
      ssl_certificate_id = "${module.cert.cert_arn}"
    },
  ]
```

**Comment by antonbabenko** [comment]
How exactly does it fail? Show the error message.

**Comment by yosefy** [comment]
* module.elb_new.aws_elb.this: "listener.0.instance_port": required field is not set
* module.elb_new.aws_elb.this: "listener.0.instance_protocol": required field is not set
* module.elb_new.aws_elb.this: "listener.0.lb_port": required field is not set
* module.elb_new.aws_elb.this: "listener.0.lb_protocol": required field is not set

**Comment by yosefy** [comment]
when i remove the ssl_certificate_id
or add it as static string, all good

**Comment by antonbabenko** [comment]
It looks like the issue is in Terraform - https://github.com/terraform-providers/terraform-provider-aws/issues/48 .

You need to make sure that you create `aws_iam_server_certificate` before passing its value to `ssl_certificate_id`. You need to avoid using calculated values (eg, data sources, resources, modules), because Terraform does not build dependency between `aws_elb` and `ssl_certificate_id` values.

This code will work:
```hcl
  listener = [
    {
      instance_port     = "8020"
      instance_protocol = "HTTP"
      lb_port           = "443"
      lb_protocol       = "SSL"
      ssl_certificate_id = "arn:aws:iam::815361859851:server-certificate/terraform-test"
    },
  ]
```

as well as this:
```hcl
  listener = [
    {
      instance_port     = "8020"
      instance_protocol = "HTTP"
      lb_port           = "443"
      lb_protocol       = "SSL"
      ssl_certificate_id = "${var.cert_arn}"
    },
  ]
# ...
}
variable "cert_arn" { default = "arn:aws:iam::815361859851:server-certificate/terraform-test" }
```

**Comment by yosefy** [comment]
Anton, question:
i create the whole core (vpc, sgs, elbs, subnets) in one play
but then i can't do it anymore because i need the cert first...

do you have an idea how to mange this?

thanks

**Comment by antonbabenko** [comment]
I would create a certificate during the first run. Create VPC and the rest in the second run. There are several things in Terraform like this, which can't be executed all-in-one. You can script this, of course.

**Comment by gnydick** [comment]
@antonbabenko , are you saying it's impossible to create a monolithic config file for a service? By that I mean, all resources are generated and so we have no actual values for anything, like vpc_id?

**Comment by antonbabenko** [comment]
@gnydick You can use a monolithic config file for a service and include data-sources in all non-complex arguments. `listener` has a complicated type `map` (or `list of maps`) and therefore computed values are not allowed there (limitation of Terraform).
