### ISSUE TITLE
access logs should be a map not a list

### ISSUE THREAD

**Issue by mgresko** [terraform-aws-modules/terraform-aws-elb#14]
```hcl
  access_logs = [
    {
      bucket = "${data.terraform_remote_state.base.logging_s3_bucket_id}"
      bucket_prefix = "${data.terraform_remote_state.base.logging_elb_prefix}"
    },
  ]
```
Error: module.app_node_primary_elb.module.elb.aws_elb.this: "access_logs.0.bucket": required field is not set

https://www.terraform.io/docs/providers/aws/r/elb.html#access_logs

**Comment by antonbabenko** [comment]
Fixed in [v2.0.0](https://github.com/terraform-aws-modules/terraform-aws-elb/releases/v2.0.0) which supports Terraform 0.12.

**Comment by ajiraj2411** [comment]
@antonbabenko I am using terraform v0.11.10.
```
  access_logs = [
    {
      bucket = "${aws_s3_bucket.logs.id}"
    },
  ]
```

I'm getting error like - **_module.elb.module.elb.aws_elb.this: "access_logs.0.bucket": required field is not set_**

In case I create a bucket before elb creation and passing the name as a string
```
  access_logs = [
    {
      bucket = "test_logs"
    },
  ]
```
it's working fine

**Comment by antonbabenko** [comment]
@AjithKumar-Raj  This is a well-known limitation that Terraform 0.11 could not use computed values everywhere. The solution is to do as you describe - create bucket before and pass the value to the module.

Terraform 0.12 has this problem fixed.
