### ISSUE TITLE
how to use ssl_certificate_id with this module

### ISSUE THREAD

**Issue by deveshmehta** [terraform-aws-modules/terraform-aws-elb#15]
When I tried to pass _**ssl_certificate_id**_ in listener

  listener = [
    {
      instance_port      = "389"
      instance_protocol  = "TCP"
      lb_port            = "636"
      lb_protocol        = "SSL"
      ssl_certificate_id = "${module.ldap_elb_certificate.arn}"
    },
  ]

```
Error: module.ldap_elb.module.elb.aws_elb.this: "listener.0.instance_port": required field is not set
Error: module.ldap_elb.module.elb.aws_elb.this: "listener.0.instance_protocol": required field is not set
Error: module.ldap_elb.module.elb.aws_elb.this: "listener.0.lb_port": required field is not set
Error: module.ldap_elb.module.elb.aws_elb.this: "listener.0.lb_protocol": required field is not set
```

**Comment by amitgera** [comment]
+1 ^ 
Ref of same issue with solution : https://github.com/hashicorp/terraform/issues/16582#issuecomment-342570913)

**Comment by UnsafePointer** [comment]
@amitgera what is the solution? Waiting for Terraform 0.12?

**Comment by antonbabenko** [comment]
Yes, this is now possible in Terraform 0.12.

I have just updated this module to support it.

Please give [v2.0.0](https://github.com/terraform-aws-modules/terraform-aws-elb/releases/v2.0.0) a try and open an issue if something is not working as expected.
