### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by sulaimanismail** [terraform-aws-modules/terraform-aws-elb#18]
Hi,
I'm having issues with ELB https://api.github.com/repos/terraform-aws-modules/terraform-aws-elb/tarball/v2.0.0?archive=tar.gz,

Error parsing .terraform\modules\d7663295c63e6e50f0f0ba502c8e8cb5\terraform-aws-modules-terraform-aws-elb-c6f9dc5\main.tf: At 7:17: Unknown token: 7:17 IDENT var.name

do I have to define variable?

**Comment by antonbabenko** [comment]
If you are using Terraform 0.11 you need to use version 1 of this module, as described here -https://github.com/terraform-aws-modules/terraform-aws-elb#terraform-versions

```hcl
module "elb_http" {
  source  = "terraform-aws-modules/elb/aws"
  version = "~> 1.0"

  # ...
}
```

**Comment by sulaimanismail** [comment]
I have followed the same step as you mention and https://github.com/terraform-aws-modules/terraform-aws-elb#terraform-versions 

but I'm still receiving the same type of error still calling V2.0 is there anything workaround?

**Comment by antonbabenko** [comment]
Make sure to remove cached directory `.terraform` and run `terraform init`.

**Comment by sulaimanismail** [comment]
> Make sure to remove cached directory `.terraform` and run `terraform init`.

I did removed .terraform dir and restart my IDE and run terraform init still same type of error I have also defined in provider.tf 

provider "terraform" {
  version = "~> 1.0"
}

am I missing anything?

**Comment by antonbabenko** [comment]
Version of Terraform modules is not the same as version of Terraform providers.

Set it like this:
```terraform
module "elb_http" {
  source  = "terraform-aws-modules/elb/aws"
  version = "~> 1.0"

  # ...
}
```

**Comment by sulaimanismail** [comment]
> Version of Terraform modules is not the same as version of Terraform providers.
> 
> Set it like this:
> 
> ```terraform
> module "elb_http" {
>   source  = "terraform-aws-modules/elb/aws"
>   version = "~> 1.0"
> 
>   # ...
> }
> ```

I have tried that also but the output was the same then I manually download and replace then I run terraform init it take everything then I get  received error on version 

 Error getting plugins: module root: module elb_http: version is not a valid parameter

I manually downloaded https://api.github.com/repos/terraform-aws-modules/terraform-aws-elb/tarball/v1.4.1?archive=tar.gz

**Comment by antonbabenko** [comment]
Please show the whole config you have.

**Comment by soumyabk** [comment]
@sulaimanismail  did you manager to resolve this? I am seeing the same issue.

**Comment by antonbabenko** [comment]
@soumyabk Please double check that you are using the correct version of this module (as described [here](https://github.com/terraform-aws-modules/terraform-aws-elb#terraform-versions)) with Terraform AWS provider and Terraform itself.

Please show which version of everything you have.

**Comment by sulaimanismail** [comment]
> @sulaimanismail did you manager to resolve this? I am seeing the same issue.

Yes I did, I was using terraform version 10, so I have to upgrade to terraform 11.x in order to work with this module.
