### ISSUE TITLE
Listeners variable use seems to be a bug that doesn't work now

### ISSUE THREAD

**Issue by evanstachowiak** [terraform-aws-modules/terraform-aws-elb#2]
Here is the issue: https://github.com/hashicorp/terraform/issues/16582

Here is the output i'm getting:
```
Error: module.elb.aws_elb.base: "listener.0.instance_port": required field is not set



Error: module.elb.aws_elb.base: "listener.0.instance_protocol": required field is not set



Error: module.elb.aws_elb.base: "listener.0.lb_port": required field is not set



Error: module.elb.aws_elb.base: "listener.0.lb_protocol": required field is not set
```
```
terraform -v
Terraform v0.11.0
```

**Comment by sysadmiral** [comment]
Please unpublish this from the registry until this is fixed?

**Comment by antonbabenko** [comment]
Yes, this is a known limitation of Terraform. It does not support dynamically computed values in nested block structures. Read this comment - https://github.com/hashicorp/terraform/issues/16582#issuecomment-342570913.

For the time being, I recommend using a static variable (`${var...}`)or hard-coded values instead of using data-sources or resources.

@sysadmiral While this module has an issue (current bug) it is working properly in general, so it won't be unpublished from the registry.

**Comment by robinbowes** [comment]
I'm seeing the same issue when I try to use a variable in the listener block. The variable is passed into the containing module having been retrieved from a data block. eg. in `main.tf` of hte module `piwik`:

```
module "elb" {
  source = "terraform-aws-modules/elb/aws"

  name = "elb-${var.name}"

  subnets         = ["${var.elb_subnets}"]
  security_groups = ["${module.security.elb_security_group}"]
  internal        = false

  listener = [
    {
      instance_port     = "80"
      instance_protocol = "HTTP"
      lb_port           = "80"
      lb_protocol       = "HTTP"
    },
    {
      instance_port      = "80"
      instance_protocol  = "HTTP"
      lb_port            = "443"
      lb_protocol        = "HTTPS"
      ssl_certificate_id = "${var.ssl_certificate_id}"
    },
  ]

  health_check = [
    {
      target              = "HTTP:80/"
      interval            = 30
      healthy_threshold   = 2
      unhealthy_threshold = 2
      timeout             = 5
    },
  ]

  number_of_instances = 1
  instances           = ["${module.instance.id}"]

  tags = "${var.tags}"
}
```

I'm passing `ssl_certificate_id` into the module having retrieved it using a data source:

```
data "aws_acm_certificate" "app_cert" {
  domain = "${var.certificate_domain}"
}

module 'piwik' {
  source = "/path/to/module"
  ...
  ssl_certificate_id    = "${data.aws_acm_certificate.app_cert.arn}"
}
```

Is there no way to make this work?

R.
