### ISSUE TITLE
No Enable/Disable Option

### ISSUE THREAD

**Issue by theeternalrat** [terraform-aws-modules/terraform-aws-elb#22]
Other AWS modules, like the ALB module, have a variable that will enable/disable the entire module. See the [ALB example](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/variables.tf#L1).

To stay in-line with other modules, I think this one should also offer such a feature.

**Comment by kefin** [comment]
I second this feature as it is useful for a project I'm working on that requires conditional creation of ELBs.

Any response/update on this?

**Comment by theeternalrat** [comment]
@kefin I wrote the required code in my currently open PR, #23. Just waiting on approval/merge, but I haven't heard anything from the maintainer(s).

**Comment by laxderek** [comment]
Keeping this active - I too want this functionality.

**Comment by laxderek** [comment]
It's been about 5 weeks. Bumping to keep this active.

**Comment by laxderek** [comment]
It seems safe to say that this repo is on life support by the bot updating the TF provider at this point.

This is such a trivial fix that has been open with a PR for going on a year now.

**Comment by antonbabenko** [comment]
[v2.4.0](https://github.com/terraform-aws-modules/terraform-aws-elb/releases/v2.4.0) has been just released... by human...

Thank you for your patience!
