### ISSUE TITLE
Error on adding SSL ceritifcate 

### ISSUE THREAD

**Issue by afreitasdotdev** [terraform-aws-modules/terraform-aws-elb#24]
Hi!

Sorry for my bad english.

I  trying use this module, but when I add an ARN from SSL certificate, this message are showing to me:

```
terraform apply myplan 

module.elb_http.module.elb.aws_elb.this: Creating...
Error: Error creating ELB: ValidationError: Secure Listeners need to specify a SSLCertificateId
        status code: 400, request id: id-for-my-request1

  on .terraform/modules/elb_http/terraform-aws-modules-terraform-aws-elb-43e3e76/modules/elb/main.tf line 1, in resource "aws_elb" "this":
   1: resource "aws_elb" "this" {

```
For test, I changing this file:

```
.terraform/modules/elb_http/terraform-aws-modules-terraform-aws-elb-43e3e76/modules/elb/main.tf
```
And, changing the **ssl_certificate_id** parameter, of **lookup(listener.value, "ssl_certificate_id", null)** to my ARN from my Certificate, the ACM module and ELB work normally.

If anyone has been through this, thank you if you can help, if it is bad configuration on my part, I apologize. 

---

## Environment configs 

+ Terraform Version: Terraform v0.12.18
+ provider.aws v2.43.0

+ ACM module version: 2.0
+ ELB_HTTP module version: 2.0

+ OS: Ubuntu 19.04

Regards!

**Comment by gstlt** [comment]
@afreitasdotdev Hey! I think I hit the same thing. Check if you added something like:
```
  listener = [
    {
      instance_port     = "80"
      instance_protocol = "HTTP"
      lb_port           = "443"
      lb_protocol       = "HTTPS"
      ssl_certificate_id = module.jenkins_dev_certificate.this_acm_certificate_arn
    },
```
Note `ssl_certificate_id`, NOT `ssl_id_certificate`.

**Comment by antonbabenko** [comment]
README has been updated some time ago to mention `ssl_certificate_id`.

Closing this issue.
