### ISSUE TITLE
"health_check" not suitable   map of string required.

### ISSUE THREAD

**Issue by andrewrotherham** [terraform-aws-modules/terraform-aws-elb#33]
HI,
I'm using a Udemy course that uses this module, but I'm getting an error  when I do a Terraform Plan ..could this just be a formatting error? I am quite new at this, could someone point me on the right direction please.....what kinds of things should I be thinking about when trying to troubleshoot this kind of thing?

 "The given value is not suitable for child module variable "health_check" defined at .terraform/modules/elb_http/variables.tf:70,1-24: map of string required.

This is my terraform code that references  it

```
module "elb_http" {

  source = "github.com/terraform-aws-modules/terraform-aws-elb.git"

  name = "elb1"

  internal = "false"

  subnets = ["subnet-a4a922cc", "subnet-8dcf0cf7"]

  security_groups = ["sg-07b2fc6c"]

  listener = [

    {

      instance_port = "80"

      instance_protocol = "HTTP"

      lb_port = "80"

      lb_protocol = "HTTP"

    },

  ]

  health_check = [

    {

      target = "HTTP:80/"

      interval = 30

      healthy_threshold = 2

      unhealthy_threshold = 2

      timeout = 5

    },

  ]

}
```

This is the variable in the module

```
variable "health_check" {
  description = "A health check block"
  type        = map(string)
}

```

**Comment by andrewrotherham** [comment]
by the way, the vendor for this Udemy is not good at getting back to you

**Comment by antonbabenko** [comment]
Hi @andrewrotherham !

I don't know which Udemy course you are talking about.

As a tip for the person learning Terraform AWS modules - always look into `examples` folder in this repository for the 100% working code.

The solution to your problem is shown there - https://github.com/terraform-aws-modules/terraform-aws-elb/blob/master/examples/complete/main.tf#L111-L117

**Comment by andrewrotherham** [comment]
great! works a treat, thanks for that Anton, will always look at examples folder going forward. I suppose [ and ] are only for lists
