### ISSUE TITLE
No way to attach ssl_certificate_id from module output- work only with plain-text based input

### ISSUE THREAD

**Issue by wnukadrian** [terraform-aws-modules/terraform-aws-elb#36]
Hello,

How I can attach ssl_certificate_id from another module output? Now module accept only plain-text based attach.

Example of ssl_certificate_id attachment
`listener = [
      {
        instance_port     = 80
        instance_protocol = "HTTP"
        lb_port           = 80
        lb_protocol       = "HTTP"
      },
      {
        instance_port     = 443
        instance_protocol = "HTTPS"
        lb_port           = 443
        lb_protocol       = "HTTPS"
        ssl_certificate_id = "${module.certificate1.cert_arn}"
      },
    ]`

And effect in apply
`+ listener {
          + instance_port     = 443
          + instance_protocol = "HTTPS"
          + lb_port           = 443
          + lb_protocol       = "HTTPS"
        }
      + listener {
          + instance_port     = 80
          + instance_protocol = "HTTP"
          + lb_port           = 80
          + lb_protocol       = "HTTP"
        }`

But when I type any plain-text based arn in ssl_certificate_id it's look like working.

**Comment by antonbabenko** [comment]
Hi,

Make sure you create a certificate before calling this module, for eg:

```
terraform apply -target=module.certificate1
terraform apply
```

**Comment by wnukadrian** [comment]
Certificate is created a long time ago.

**Comment by wnukadrian** [comment]
Okay, I define wrong cert for not correct environment...
