### ISSUE TITLE
Warning: Provider source not supported in Terraform v0.12

### ISSUE THREAD

**Issue by spatel96** [terraform-aws-modules/terraform-aws-elb#37]
I believe the new addition of the provider source is causing terraform validate checks to throw warnings.

If we want to include this change it would also need a version bump to terraform 0.13

```hcl
Warning: Provider source not supported in Terraform v0.12

  on .terraform/modules/elb/modules/elb_attachment/versions.tf line 5, in terraform:
   5:     aws = {
   6:       source  = "hashicorp/aws"
   7:       version = ">= 2.20"
   8:     }

A source was declared for provider aws. Terraform v0.12 does not support the
provider source attribute. It will be ignored.
```

https://github.com/terraform-aws-modules/terraform-aws-elb/blob/78b026a63b52325c5420fcb2ed7ff1a6da3a213c/versions.tf#L6

**Comment by bryantbiggs** [comment]
hi @spatel96 - its only a warning and still functions as intended
