### ISSUE TITLE
Using a datasource for the ssl_certificate_id in the listener breaks the module

### ISSUE THREAD

**Issue by horsey** [terraform-aws-modules/terraform-aws-elb#5]
Hello @antonbabenko 
In a particular case where one can use a manually configured ```ssl_certificate_id``` in the  ELB listener parameter in the following manner, breaks the module. 
The listener configuration code below does not work as expected. 
```
listener = [
    {
      instance_port     = "80"
      instance_protocol = "HTTP"
      lb_port           = "80"
      lb_protocol       = "HTTP"
    },
    {
      instance_port     = "8443"
      instance_protocol = "HTTPS"
      lb_port           = "8443"
      lb_protocol       = "HTTPS"
      ssl_certificate_id = "${data.aws_acm_certificate.elb_cert.arn}"
    },
  ]
```
Above configuration throws an error: 
```
Error: module.elb.module.elb.aws_elb.this: "listener.0.instance_port": required field is not set
Error: module.elb.module.elb.aws_elb.this: "listener.0.instance_protocol": required field is not set
Error: module.elb.module.elb.aws_elb.this: "listener.0.lb_port": required field is not set
Error: module.elb.module.elb.aws_elb.this: "listener.0.lb_protocol": required field is not set
```

Where as below  configuration works fine:
````
listener = [
    {
      instance_port     = "80"
      instance_protocol = "HTTP"
      lb_port           = "80"
      lb_protocol       = "HTTP"
    },
    {
      instance_port     = "8443"
      instance_protocol = "HTTPS"
      lb_port           = "8443"
      lb_protocol       = "HTTPS"
      ssl_certificate_id = "arn:aws:acm:us-east-1:xxxxxxxxxxxxxx:certificate/xxxxxxxxxxxxxxxxxxxxxxxxxx"                                                                    
    },
  ]
````
I have opened an issue in the Terraform repository regarding the same: https://github.com/hashicorp/terraform/issues/17292

**Comment by antonbabenko** [comment]
Yes, it is a known issue and a limitation.

**Comment by horsey** [comment]
@antonbabenko  All the previously closed issues are related to this one. I should have known. Maybe a note in the README will help because this is a common scenario to have.

**Comment by antonbabenko** [comment]
Agree, good idea, PR is welcome :)

**Comment by GElkayam** [comment]
Been banging my head for the last two hours trying to make it work. no luck. 
is there any ETA of a fix / support for this use case?

**Comment by antonbabenko** [comment]
@GElkayam Unfortunately there is no ETA as far as I know. HCL2 is in development right now, so 🤞 to have it ready soon.

**Comment by oryband** [comment]
linking related issues for the sake of documentation:
- https://github.com/hashicorp/terraform/issues/17292
- https://github.com/hashicorp/terraform/issues/16582

**Comment by gaui** [comment]
Related: https://github.com/terraform-providers/terraform-provider-null/issues/18
