### ISSUE TITLE
pattern for adding autoscaling group instances

### ISSUE THREAD

**Issue by rojomisin** [terraform-aws-modules/terraform-aws-elb#7]
Is there a way to attach autoscaled instances?

**Comment by antonbabenko** [comment]
There are at least two ways to do this:
1. Find ID of instances using data-source [aws_instances](https://www.terraform.io/docs/providers/aws/d/instances.html) and pass it as an argument to [elb_attachment module](https://github.com/terraform-aws-modules/terraform-aws-elb/tree/master/modules/elb_attachment)
2. Integrate ASG with an ELB as shown in [this example](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/examples/asg_elb/main.tf#L58) in [terraform-aws-autoscaling module](https://github.com/terraform-aws-modules/terraform-aws-autoscaling)

Normally the second option is easier and works better.
